### ISSUE TITLE
Write/Read Characteristic

### ISSUE THREAD

**Issue by tilersmyth** [spacecheese/bluez_peripheral#24]
My gatt client sends a write request that is looking for a response and I'm using something like the following code:
```
@characteristic(uuid, CharFlags.WRITE | CharFlags.READ)
def on_read(self):
    return bytes("read value", "utf-8")

    
@on_wifiscan_request.setter
def on_write(self, value, options):
    print("write value: ", value)
```
Shouldn't this work? The write part works but nothing is returned. I'm sure I'm missing something but I've been racking my brain trying to figure this out and I couldn't find an example to handle this scenario.  thanks for any help.

**Comment by spacecheese** [comment]
Hi. To confirm you're trying to implement a write followed by some kind of callback? A write | read won't do this- the read also needs triggering by the client. You could probably do this with a write | notify though your client will need to subscribe to the characteristic.
