### ISSUE TITLE
DBusError: Failed to parse advertisement

### ISSUE THREAD

**Issue by wejedge** [spacecheese/bluez_peripheral#34]
Hi,
for the life of me I can't get this to work. I must be doing something wrong?

advert = Advertisement("My Peripheral", [], 0, 60, serviceData={'11223344':b'\0x01'})

**Comment by spacecheese** [comment]
Hello, thanks for the report. The serviceData type was wrong internally should be fixed in the PR (if you could confirm it works for you)
`pip install -e git+https://github.com/spacecheese/bluez_peripheral.git@fix-service-data#egg=bluez_peripheral`

**Comment by wejedge** [comment]
Hey there, thanks for the quick reply. Yes that update works lovely. Keep up the good work. ;)
