### ISSUE TITLE
How to declare a service with a READ & WRITE characteristic ?

### ISSUE THREAD

**Issue by ubicore** [spacecheese/bluez_peripheral#8]
Hello,

I am trying to declare a service with a READ & WRITE characteristic, and with it's setter and getter functions.

But if i declare it, i have an error either :
- on READ if getter returns non-byte type value as type expected is "bytes" to be compliant with the signature
- on WRITE as  "'bytes' object does not support item assignment"

I found  that the same "self._value" is used for ReadValue and WriteValue method in the characteristic class and it could not be at the same time of type "bytes" (after a READ call) and support the item assignement (in a WRITE call).

Did i miss something ?
Thanks

**Comment by spacecheese** [comment]
Sorry for the slow response. Fixed by [e584370](https://github.com/spacecheese/bluez_peripheral/commit/e584370188065ff0faf19b9c2f75442e2c2c73fd).

**Comment by ubicore** [comment]
Thanks for the changes.
